/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.7.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *actionFile;
    QWidget *centralWidget;
    QFrame *frame_info;
    QLabel *label;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_10;
    QComboBox *comboBox;
    QComboBox *comboBox_2;
    QComboBox *comboBox_3;
    QComboBox *comboBox_4;
    QPushButton *pushButton;
    QPushButton *pushButton_2;
    QPushButton *pushButton_3;
    QPushButton *pushButton_4;
    QPushButton *pushButton_5;
    QPushButton *pushButton_6;
    QFrame *frame_trabajos;
    QLabel *label_2;
    QTableWidget *tabla_tareas;
    QFrame *frame_cpu;
    QLabel *label_3;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_19;
    QLabel *label_20;
    QLabel *label_21;
    QFrame *frame_cola;
    QLabel *label_4;
    QLabel *label_24;
    QLabel *label_16;
    QLabel *label_17;
    QFrame *frame_promedio;
    QLabel *label_5;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_22;
    QLabel *label_23;
    QFrame *frame_info_5;
    QLabel *label_6;
    QLabel *label_18;
    QLabel *label_25;
    QLabel *label_26;
    QLabel *label_27;
    QLabel *label_36;
    QLabel *label_34;
    QLabel *label_35;
    QLabel *label_33;
    QLabel *label_37;
    QLabel *label_38;
    QLabel *label_39;
    QLabel *label_40;
    QLabel *label_41;
    QLabel *label_42;
    QLabel *label_43;
    QLabel *label_44;
    QStatusBar *statusBar;
    QMenuBar *menuBar;
    QMenu *menuPlanificador_de_Procesos_CSUNSA;
    QMenu *menuAyuda;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(994, 519);
        actionFile = new QAction(MainWindow);
        actionFile->setObjectName(QStringLiteral("actionFile"));
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        frame_info = new QFrame(centralWidget);
        frame_info->setObjectName(QStringLiteral("frame_info"));
        frame_info->setGeometry(QRect(10, 10, 421, 221));
        frame_info->setFrameShape(QFrame::Panel);
        frame_info->setFrameShadow(QFrame::Raised);
        label = new QLabel(frame_info);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(10, 10, 91, 21));
        QPalette palette;
        QBrush brush(QColor(255, 0, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        QBrush brush1(QColor(255, 255, 255, 127));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        label->setPalette(palette);
        QFont font;
        font.setFamily(QStringLiteral("Ubuntu"));
        font.setPointSize(12);
        font.setBold(true);
        font.setWeight(75);
        label->setFont(font);
        label_7 = new QLabel(frame_info);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(10, 50, 81, 21));
        QPalette palette1;
        QBrush brush2(QColor(0, 0, 0, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        label_7->setPalette(palette1);
        QFont font1;
        font1.setFamily(QStringLiteral("Ubuntu"));
        font1.setPointSize(10);
        font1.setBold(true);
        font1.setItalic(false);
        font1.setWeight(75);
        label_7->setFont(font1);
        label_8 = new QLabel(frame_info);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(110, 50, 81, 21));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        label_8->setPalette(palette2);
        label_8->setFont(font1);
        label_9 = new QLabel(frame_info);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(210, 50, 111, 21));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        label_9->setPalette(palette3);
        label_9->setFont(font1);
        label_10 = new QLabel(frame_info);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(330, 50, 81, 21));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        label_10->setPalette(palette4);
        label_10->setFont(font1);
        comboBox = new QComboBox(frame_info);
        comboBox->setObjectName(QStringLiteral("comboBox"));
        comboBox->setGeometry(QRect(10, 80, 79, 22));
        comboBox_2 = new QComboBox(frame_info);
        comboBox_2->setObjectName(QStringLiteral("comboBox_2"));
        comboBox_2->setGeometry(QRect(110, 80, 79, 22));
        comboBox_3 = new QComboBox(frame_info);
        comboBox_3->setObjectName(QStringLiteral("comboBox_3"));
        comboBox_3->setGeometry(QRect(210, 80, 101, 22));
        comboBox_4 = new QComboBox(frame_info);
        comboBox_4->setObjectName(QStringLiteral("comboBox_4"));
        comboBox_4->setGeometry(QRect(330, 80, 79, 22));
        pushButton = new QPushButton(frame_info);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(10, 110, 80, 22));
        pushButton_2 = new QPushButton(frame_info);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(110, 110, 80, 22));
        pushButton_3 = new QPushButton(frame_info);
        pushButton_3->setObjectName(QStringLiteral("pushButton_3"));
        pushButton_3->setGeometry(QRect(210, 110, 111, 22));
        pushButton_4 = new QPushButton(frame_info);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(330, 110, 80, 22));
        pushButton_5 = new QPushButton(frame_info);
        pushButton_5->setObjectName(QStringLiteral("pushButton_5"));
        pushButton_5->setGeometry(QRect(20, 150, 191, 22));
        pushButton_6 = new QPushButton(frame_info);
        pushButton_6->setObjectName(QStringLiteral("pushButton_6"));
        pushButton_6->setGeometry(QRect(220, 150, 181, 22));
        frame_trabajos = new QFrame(centralWidget);
        frame_trabajos->setObjectName(QStringLiteral("frame_trabajos"));
        frame_trabajos->setGeometry(QRect(440, 10, 541, 221));
        frame_trabajos->setFrameShape(QFrame::Panel);
        frame_trabajos->setFrameShadow(QFrame::Raised);
        label_2 = new QLabel(frame_trabajos);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(10, 10, 101, 21));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        label_2->setPalette(palette5);
        label_2->setFont(font);
        tabla_tareas = new QTableWidget(frame_trabajos);
        if (tabla_tareas->columnCount() < 10)
            tabla_tareas->setColumnCount(10);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        tabla_tareas->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        tabla_tareas->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        tabla_tareas->setHorizontalHeaderItem(2, __qtablewidgetitem2);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        tabla_tareas->setHorizontalHeaderItem(3, __qtablewidgetitem3);
        QTableWidgetItem *__qtablewidgetitem4 = new QTableWidgetItem();
        tabla_tareas->setHorizontalHeaderItem(4, __qtablewidgetitem4);
        QTableWidgetItem *__qtablewidgetitem5 = new QTableWidgetItem();
        tabla_tareas->setHorizontalHeaderItem(5, __qtablewidgetitem5);
        QTableWidgetItem *__qtablewidgetitem6 = new QTableWidgetItem();
        tabla_tareas->setHorizontalHeaderItem(6, __qtablewidgetitem6);
        QTableWidgetItem *__qtablewidgetitem7 = new QTableWidgetItem();
        tabla_tareas->setHorizontalHeaderItem(7, __qtablewidgetitem7);
        QTableWidgetItem *__qtablewidgetitem8 = new QTableWidgetItem();
        tabla_tareas->setHorizontalHeaderItem(8, __qtablewidgetitem8);
        QTableWidgetItem *__qtablewidgetitem9 = new QTableWidgetItem();
        tabla_tareas->setHorizontalHeaderItem(9, __qtablewidgetitem9);
        if (tabla_tareas->rowCount() < 9)
            tabla_tareas->setRowCount(9);
        QTableWidgetItem *__qtablewidgetitem10 = new QTableWidgetItem();
        tabla_tareas->setVerticalHeaderItem(0, __qtablewidgetitem10);
        QTableWidgetItem *__qtablewidgetitem11 = new QTableWidgetItem();
        tabla_tareas->setVerticalHeaderItem(1, __qtablewidgetitem11);
        QTableWidgetItem *__qtablewidgetitem12 = new QTableWidgetItem();
        tabla_tareas->setVerticalHeaderItem(2, __qtablewidgetitem12);
        QTableWidgetItem *__qtablewidgetitem13 = new QTableWidgetItem();
        tabla_tareas->setVerticalHeaderItem(3, __qtablewidgetitem13);
        QTableWidgetItem *__qtablewidgetitem14 = new QTableWidgetItem();
        tabla_tareas->setVerticalHeaderItem(4, __qtablewidgetitem14);
        QTableWidgetItem *__qtablewidgetitem15 = new QTableWidgetItem();
        tabla_tareas->setVerticalHeaderItem(5, __qtablewidgetitem15);
        QTableWidgetItem *__qtablewidgetitem16 = new QTableWidgetItem();
        tabla_tareas->setVerticalHeaderItem(6, __qtablewidgetitem16);
        QTableWidgetItem *__qtablewidgetitem17 = new QTableWidgetItem();
        tabla_tareas->setVerticalHeaderItem(7, __qtablewidgetitem17);
        QTableWidgetItem *__qtablewidgetitem18 = new QTableWidgetItem();
        tabla_tareas->setVerticalHeaderItem(8, __qtablewidgetitem18);
        QTableWidgetItem *__qtablewidgetitem19 = new QTableWidgetItem();
        tabla_tareas->setItem(0, 0, __qtablewidgetitem19);
        QTableWidgetItem *__qtablewidgetitem20 = new QTableWidgetItem();
        tabla_tareas->setItem(0, 1, __qtablewidgetitem20);
        tabla_tareas->setObjectName(QStringLiteral("tabla_tareas"));
        tabla_tareas->setGeometry(QRect(10, 30, 521, 181));
        tabla_tareas->setSizeAdjustPolicy(QAbstractScrollArea::AdjustToContents);
        tabla_tareas->setAlternatingRowColors(false);
        tabla_tareas->horizontalHeader()->setStretchLastSection(true);
        frame_cpu = new QFrame(centralWidget);
        frame_cpu->setObjectName(QStringLiteral("frame_cpu"));
        frame_cpu->setGeometry(QRect(10, 240, 451, 101));
        frame_cpu->setFrameShape(QFrame::Panel);
        frame_cpu->setFrameShadow(QFrame::Raised);
        label_3 = new QLabel(frame_cpu);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(10, 10, 91, 21));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        label_3->setPalette(palette6);
        label_3->setFont(font);
        label_11 = new QLabel(frame_cpu);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(10, 30, 81, 21));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette7.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        label_11->setPalette(palette7);
        label_11->setFont(font1);
        label_12 = new QLabel(frame_cpu);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(160, 30, 101, 21));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette8.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette8.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        label_12->setPalette(palette8);
        label_12->setFont(font1);
        label_13 = new QLabel(frame_cpu);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(300, 30, 81, 21));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette9.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette9.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        label_13->setPalette(palette9);
        label_13->setFont(font1);
        label_19 = new QLabel(frame_cpu);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(20, 60, 81, 21));
        QPalette palette10;
        palette10.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette10.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette10.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        label_19->setPalette(palette10);
        QFont font2;
        font2.setFamily(QStringLiteral("Ubuntu"));
        font2.setPointSize(14);
        font2.setBold(true);
        font2.setItalic(false);
        font2.setWeight(75);
        label_19->setFont(font2);
        label_20 = new QLabel(frame_cpu);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(190, 60, 81, 16));
        QPalette palette11;
        palette11.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette11.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette11.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        label_20->setPalette(palette11);
        label_20->setFont(font2);
        label_21 = new QLabel(frame_cpu);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(300, 60, 81, 16));
        QPalette palette12;
        palette12.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette12.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette12.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        label_21->setPalette(palette12);
        label_21->setFont(font2);
        frame_cola = new QFrame(centralWidget);
        frame_cola->setObjectName(QStringLiteral("frame_cola"));
        frame_cola->setGeometry(QRect(470, 240, 241, 101));
        frame_cola->setFrameShape(QFrame::Panel);
        frame_cola->setFrameShadow(QFrame::Raised);
        label_4 = new QLabel(frame_cola);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(10, 10, 91, 21));
        QPalette palette13;
        palette13.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette13.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        label_4->setPalette(palette13);
        label_4->setFont(font);
        label_24 = new QLabel(frame_cola);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(10, 60, 81, 16));
        QPalette palette14;
        palette14.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette14.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette14.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        label_24->setPalette(palette14);
        label_24->setFont(font2);
        label_16 = new QLabel(frame_cola);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(50, 40, 31, 51));
        QPalette palette15;
        palette15.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        QBrush brush3(QColor(0, 255, 0, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette15.setBrush(QPalette::Active, QPalette::Button, brush3);
        palette15.setBrush(QPalette::Active, QPalette::Light, brush3);
        QBrush brush4(QColor(0, 212, 0, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette15.setBrush(QPalette::Active, QPalette::Midlight, brush4);
        QBrush brush5(QColor(0, 85, 0, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette15.setBrush(QPalette::Active, QPalette::Dark, brush5);
        QBrush brush6(QColor(0, 113, 0, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette15.setBrush(QPalette::Active, QPalette::Mid, brush6);
        palette15.setBrush(QPalette::Active, QPalette::Text, brush2);
        QBrush brush7(QColor(255, 255, 255, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette15.setBrush(QPalette::Active, QPalette::BrightText, brush7);
        palette15.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette15.setBrush(QPalette::Active, QPalette::Base, brush3);
        palette15.setBrush(QPalette::Active, QPalette::Window, brush3);
        palette15.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        QBrush brush8(QColor(127, 212, 127, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette15.setBrush(QPalette::Active, QPalette::AlternateBase, brush8);
        QBrush brush9(QColor(255, 255, 220, 255));
        brush9.setStyle(Qt::SolidPattern);
        palette15.setBrush(QPalette::Active, QPalette::ToolTipBase, brush9);
        palette15.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
        palette15.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette15.setBrush(QPalette::Inactive, QPalette::Button, brush3);
        palette15.setBrush(QPalette::Inactive, QPalette::Light, brush3);
        palette15.setBrush(QPalette::Inactive, QPalette::Midlight, brush4);
        palette15.setBrush(QPalette::Inactive, QPalette::Dark, brush5);
        palette15.setBrush(QPalette::Inactive, QPalette::Mid, brush6);
        palette15.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette15.setBrush(QPalette::Inactive, QPalette::BrightText, brush7);
        palette15.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette15.setBrush(QPalette::Inactive, QPalette::Base, brush3);
        palette15.setBrush(QPalette::Inactive, QPalette::Window, brush3);
        palette15.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette15.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush8);
        palette15.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush9);
        palette15.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
        palette15.setBrush(QPalette::Disabled, QPalette::WindowText, brush5);
        palette15.setBrush(QPalette::Disabled, QPalette::Button, brush3);
        palette15.setBrush(QPalette::Disabled, QPalette::Light, brush3);
        palette15.setBrush(QPalette::Disabled, QPalette::Midlight, brush4);
        palette15.setBrush(QPalette::Disabled, QPalette::Dark, brush5);
        palette15.setBrush(QPalette::Disabled, QPalette::Mid, brush6);
        palette15.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette15.setBrush(QPalette::Disabled, QPalette::BrightText, brush7);
        palette15.setBrush(QPalette::Disabled, QPalette::ButtonText, brush5);
        palette15.setBrush(QPalette::Disabled, QPalette::Base, brush3);
        palette15.setBrush(QPalette::Disabled, QPalette::Window, brush3);
        palette15.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        QBrush brush10(QColor(0, 170, 0, 255));
        brush10.setStyle(Qt::SolidPattern);
        palette15.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush10);
        palette15.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush9);
        palette15.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
        label_16->setPalette(palette15);
        label_16->setStyleSheet(QStringLiteral("background-color : rgb(0, 255, 0);"));
        label_16->setAlignment(Qt::AlignCenter);
        label_17 = new QLabel(frame_cola);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(90, 40, 31, 51));
        QPalette palette16;
        palette16.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        QBrush brush11(QColor(0, 85, 127, 255));
        brush11.setStyle(Qt::SolidPattern);
        palette16.setBrush(QPalette::Active, QPalette::Button, brush11);
        palette16.setBrush(QPalette::Active, QPalette::Light, brush3);
        palette16.setBrush(QPalette::Active, QPalette::Midlight, brush4);
        palette16.setBrush(QPalette::Active, QPalette::Dark, brush5);
        palette16.setBrush(QPalette::Active, QPalette::Mid, brush6);
        palette16.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette16.setBrush(QPalette::Active, QPalette::BrightText, brush7);
        palette16.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette16.setBrush(QPalette::Active, QPalette::Base, brush11);
        palette16.setBrush(QPalette::Active, QPalette::Window, brush11);
        palette16.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette16.setBrush(QPalette::Active, QPalette::AlternateBase, brush8);
        palette16.setBrush(QPalette::Active, QPalette::ToolTipBase, brush9);
        palette16.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
        palette16.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette16.setBrush(QPalette::Inactive, QPalette::Button, brush11);
        palette16.setBrush(QPalette::Inactive, QPalette::Light, brush3);
        palette16.setBrush(QPalette::Inactive, QPalette::Midlight, brush4);
        palette16.setBrush(QPalette::Inactive, QPalette::Dark, brush5);
        palette16.setBrush(QPalette::Inactive, QPalette::Mid, brush6);
        palette16.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette16.setBrush(QPalette::Inactive, QPalette::BrightText, brush7);
        palette16.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette16.setBrush(QPalette::Inactive, QPalette::Base, brush11);
        palette16.setBrush(QPalette::Inactive, QPalette::Window, brush11);
        palette16.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette16.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush8);
        palette16.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush9);
        palette16.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
        palette16.setBrush(QPalette::Disabled, QPalette::WindowText, brush5);
        palette16.setBrush(QPalette::Disabled, QPalette::Button, brush11);
        palette16.setBrush(QPalette::Disabled, QPalette::Light, brush3);
        palette16.setBrush(QPalette::Disabled, QPalette::Midlight, brush4);
        palette16.setBrush(QPalette::Disabled, QPalette::Dark, brush5);
        palette16.setBrush(QPalette::Disabled, QPalette::Mid, brush6);
        palette16.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette16.setBrush(QPalette::Disabled, QPalette::BrightText, brush7);
        palette16.setBrush(QPalette::Disabled, QPalette::ButtonText, brush5);
        palette16.setBrush(QPalette::Disabled, QPalette::Base, brush11);
        palette16.setBrush(QPalette::Disabled, QPalette::Window, brush11);
        palette16.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette16.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush10);
        palette16.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush9);
        palette16.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
        label_17->setPalette(palette16);
        label_17->setStyleSheet(QStringLiteral("background-color : rgb(0, 85, 127);"));
        label_17->setAlignment(Qt::AlignCenter);
        frame_promedio = new QFrame(centralWidget);
        frame_promedio->setObjectName(QStringLiteral("frame_promedio"));
        frame_promedio->setGeometry(QRect(720, 240, 261, 101));
        frame_promedio->setFrameShape(QFrame::Panel);
        frame_promedio->setFrameShadow(QFrame::Raised);
        label_5 = new QLabel(frame_promedio);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(10, 10, 91, 21));
        QPalette palette17;
        palette17.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette17.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette17.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        label_5->setPalette(palette17);
        label_5->setFont(font);
        label_14 = new QLabel(frame_promedio);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(30, 30, 81, 21));
        QPalette palette18;
        palette18.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette18.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette18.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        label_14->setPalette(palette18);
        label_14->setFont(font1);
        label_15 = new QLabel(frame_promedio);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(150, 30, 81, 21));
        QPalette palette19;
        palette19.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette19.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette19.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        label_15->setPalette(palette19);
        label_15->setFont(font1);
        label_22 = new QLabel(frame_promedio);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(40, 70, 81, 16));
        QPalette palette20;
        palette20.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette20.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette20.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        label_22->setPalette(palette20);
        label_22->setFont(font2);
        label_23 = new QLabel(frame_promedio);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(150, 70, 81, 16));
        QPalette palette21;
        palette21.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette21.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette21.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        label_23->setPalette(palette21);
        label_23->setFont(font2);
        frame_info_5 = new QFrame(centralWidget);
        frame_info_5->setObjectName(QStringLiteral("frame_info_5"));
        frame_info_5->setGeometry(QRect(10, 350, 971, 121));
        frame_info_5->setFrameShape(QFrame::Panel);
        frame_info_5->setFrameShadow(QFrame::Raised);
        label_6 = new QLabel(frame_info_5);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(10, 10, 121, 21));
        QPalette palette22;
        palette22.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette22.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette22.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        label_6->setPalette(palette22);
        label_6->setFont(font);
        label_18 = new QLabel(frame_info_5);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(10, 40, 16, 71));
        QPalette palette23;
        palette23.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette23.setBrush(QPalette::Active, QPalette::Button, brush);
        palette23.setBrush(QPalette::Active, QPalette::Light, brush3);
        palette23.setBrush(QPalette::Active, QPalette::Midlight, brush4);
        palette23.setBrush(QPalette::Active, QPalette::Dark, brush5);
        palette23.setBrush(QPalette::Active, QPalette::Mid, brush6);
        palette23.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette23.setBrush(QPalette::Active, QPalette::BrightText, brush7);
        palette23.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette23.setBrush(QPalette::Active, QPalette::Base, brush);
        palette23.setBrush(QPalette::Active, QPalette::Window, brush);
        palette23.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette23.setBrush(QPalette::Active, QPalette::AlternateBase, brush8);
        palette23.setBrush(QPalette::Active, QPalette::ToolTipBase, brush9);
        palette23.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
        palette23.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette23.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette23.setBrush(QPalette::Inactive, QPalette::Light, brush3);
        palette23.setBrush(QPalette::Inactive, QPalette::Midlight, brush4);
        palette23.setBrush(QPalette::Inactive, QPalette::Dark, brush5);
        palette23.setBrush(QPalette::Inactive, QPalette::Mid, brush6);
        palette23.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette23.setBrush(QPalette::Inactive, QPalette::BrightText, brush7);
        palette23.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette23.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette23.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette23.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette23.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush8);
        palette23.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush9);
        palette23.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
        palette23.setBrush(QPalette::Disabled, QPalette::WindowText, brush5);
        palette23.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette23.setBrush(QPalette::Disabled, QPalette::Light, brush3);
        palette23.setBrush(QPalette::Disabled, QPalette::Midlight, brush4);
        palette23.setBrush(QPalette::Disabled, QPalette::Dark, brush5);
        palette23.setBrush(QPalette::Disabled, QPalette::Mid, brush6);
        palette23.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette23.setBrush(QPalette::Disabled, QPalette::BrightText, brush7);
        palette23.setBrush(QPalette::Disabled, QPalette::ButtonText, brush5);
        palette23.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette23.setBrush(QPalette::Disabled, QPalette::Window, brush);
        palette23.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette23.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush10);
        palette23.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush9);
        palette23.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
        label_18->setPalette(palette23);
        label_18->setStyleSheet(QStringLiteral("background-color : rgb(255, 0, 0);"));
        label_18->setAlignment(Qt::AlignCenter);
        label_25 = new QLabel(frame_info_5);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(30, 40, 16, 71));
        QPalette palette24;
        palette24.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette24.setBrush(QPalette::Active, QPalette::Button, brush);
        palette24.setBrush(QPalette::Active, QPalette::Light, brush3);
        palette24.setBrush(QPalette::Active, QPalette::Midlight, brush4);
        palette24.setBrush(QPalette::Active, QPalette::Dark, brush5);
        palette24.setBrush(QPalette::Active, QPalette::Mid, brush6);
        palette24.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette24.setBrush(QPalette::Active, QPalette::BrightText, brush7);
        palette24.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette24.setBrush(QPalette::Active, QPalette::Base, brush);
        palette24.setBrush(QPalette::Active, QPalette::Window, brush);
        palette24.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette24.setBrush(QPalette::Active, QPalette::AlternateBase, brush8);
        palette24.setBrush(QPalette::Active, QPalette::ToolTipBase, brush9);
        palette24.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
        palette24.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette24.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette24.setBrush(QPalette::Inactive, QPalette::Light, brush3);
        palette24.setBrush(QPalette::Inactive, QPalette::Midlight, brush4);
        palette24.setBrush(QPalette::Inactive, QPalette::Dark, brush5);
        palette24.setBrush(QPalette::Inactive, QPalette::Mid, brush6);
        palette24.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette24.setBrush(QPalette::Inactive, QPalette::BrightText, brush7);
        palette24.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette24.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette24.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette24.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette24.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush8);
        palette24.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush9);
        palette24.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
        palette24.setBrush(QPalette::Disabled, QPalette::WindowText, brush5);
        palette24.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette24.setBrush(QPalette::Disabled, QPalette::Light, brush3);
        palette24.setBrush(QPalette::Disabled, QPalette::Midlight, brush4);
        palette24.setBrush(QPalette::Disabled, QPalette::Dark, brush5);
        palette24.setBrush(QPalette::Disabled, QPalette::Mid, brush6);
        palette24.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette24.setBrush(QPalette::Disabled, QPalette::BrightText, brush7);
        palette24.setBrush(QPalette::Disabled, QPalette::ButtonText, brush5);
        palette24.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette24.setBrush(QPalette::Disabled, QPalette::Window, brush);
        palette24.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette24.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush10);
        palette24.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush9);
        palette24.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
        label_25->setPalette(palette24);
        label_25->setStyleSheet(QStringLiteral("background-color : rgb(255, 0, 0);"));
        label_25->setAlignment(Qt::AlignCenter);
        label_26 = new QLabel(frame_info_5);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(50, 40, 16, 71));
        QPalette palette25;
        palette25.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette25.setBrush(QPalette::Active, QPalette::Button, brush);
        palette25.setBrush(QPalette::Active, QPalette::Light, brush3);
        palette25.setBrush(QPalette::Active, QPalette::Midlight, brush4);
        palette25.setBrush(QPalette::Active, QPalette::Dark, brush5);
        palette25.setBrush(QPalette::Active, QPalette::Mid, brush6);
        palette25.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette25.setBrush(QPalette::Active, QPalette::BrightText, brush7);
        palette25.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette25.setBrush(QPalette::Active, QPalette::Base, brush);
        palette25.setBrush(QPalette::Active, QPalette::Window, brush);
        palette25.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette25.setBrush(QPalette::Active, QPalette::AlternateBase, brush8);
        palette25.setBrush(QPalette::Active, QPalette::ToolTipBase, brush9);
        palette25.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
        palette25.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette25.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette25.setBrush(QPalette::Inactive, QPalette::Light, brush3);
        palette25.setBrush(QPalette::Inactive, QPalette::Midlight, brush4);
        palette25.setBrush(QPalette::Inactive, QPalette::Dark, brush5);
        palette25.setBrush(QPalette::Inactive, QPalette::Mid, brush6);
        palette25.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette25.setBrush(QPalette::Inactive, QPalette::BrightText, brush7);
        palette25.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette25.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette25.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette25.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette25.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush8);
        palette25.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush9);
        palette25.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
        palette25.setBrush(QPalette::Disabled, QPalette::WindowText, brush5);
        palette25.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette25.setBrush(QPalette::Disabled, QPalette::Light, brush3);
        palette25.setBrush(QPalette::Disabled, QPalette::Midlight, brush4);
        palette25.setBrush(QPalette::Disabled, QPalette::Dark, brush5);
        palette25.setBrush(QPalette::Disabled, QPalette::Mid, brush6);
        palette25.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette25.setBrush(QPalette::Disabled, QPalette::BrightText, brush7);
        palette25.setBrush(QPalette::Disabled, QPalette::ButtonText, brush5);
        palette25.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette25.setBrush(QPalette::Disabled, QPalette::Window, brush);
        palette25.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette25.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush10);
        palette25.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush9);
        palette25.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
        label_26->setPalette(palette25);
        label_26->setStyleSheet(QStringLiteral("background-color : rgb(255, 0, 0);"));
        label_26->setAlignment(Qt::AlignCenter);
        label_27 = new QLabel(frame_info_5);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(70, 40, 16, 71));
        QPalette palette26;
        palette26.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette26.setBrush(QPalette::Active, QPalette::Button, brush);
        palette26.setBrush(QPalette::Active, QPalette::Light, brush3);
        palette26.setBrush(QPalette::Active, QPalette::Midlight, brush4);
        palette26.setBrush(QPalette::Active, QPalette::Dark, brush5);
        palette26.setBrush(QPalette::Active, QPalette::Mid, brush6);
        palette26.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette26.setBrush(QPalette::Active, QPalette::BrightText, brush7);
        palette26.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette26.setBrush(QPalette::Active, QPalette::Base, brush);
        palette26.setBrush(QPalette::Active, QPalette::Window, brush);
        palette26.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette26.setBrush(QPalette::Active, QPalette::AlternateBase, brush8);
        palette26.setBrush(QPalette::Active, QPalette::ToolTipBase, brush9);
        palette26.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
        palette26.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette26.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette26.setBrush(QPalette::Inactive, QPalette::Light, brush3);
        palette26.setBrush(QPalette::Inactive, QPalette::Midlight, brush4);
        palette26.setBrush(QPalette::Inactive, QPalette::Dark, brush5);
        palette26.setBrush(QPalette::Inactive, QPalette::Mid, brush6);
        palette26.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette26.setBrush(QPalette::Inactive, QPalette::BrightText, brush7);
        palette26.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette26.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette26.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette26.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette26.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush8);
        palette26.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush9);
        palette26.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
        palette26.setBrush(QPalette::Disabled, QPalette::WindowText, brush5);
        palette26.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette26.setBrush(QPalette::Disabled, QPalette::Light, brush3);
        palette26.setBrush(QPalette::Disabled, QPalette::Midlight, brush4);
        palette26.setBrush(QPalette::Disabled, QPalette::Dark, brush5);
        palette26.setBrush(QPalette::Disabled, QPalette::Mid, brush6);
        palette26.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette26.setBrush(QPalette::Disabled, QPalette::BrightText, brush7);
        palette26.setBrush(QPalette::Disabled, QPalette::ButtonText, brush5);
        palette26.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette26.setBrush(QPalette::Disabled, QPalette::Window, brush);
        palette26.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette26.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush10);
        palette26.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush9);
        palette26.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
        label_27->setPalette(palette26);
        label_27->setStyleSheet(QStringLiteral("background-color : rgb(255, 0, 0);"));
        label_27->setAlignment(Qt::AlignCenter);
        label_36 = new QLabel(frame_info_5);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(90, 40, 16, 71));
        QPalette palette27;
        palette27.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        QBrush brush12(QColor(255, 170, 0, 255));
        brush12.setStyle(Qt::SolidPattern);
        palette27.setBrush(QPalette::Active, QPalette::Button, brush12);
        palette27.setBrush(QPalette::Active, QPalette::Light, brush3);
        palette27.setBrush(QPalette::Active, QPalette::Midlight, brush4);
        palette27.setBrush(QPalette::Active, QPalette::Dark, brush5);
        palette27.setBrush(QPalette::Active, QPalette::Mid, brush6);
        palette27.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette27.setBrush(QPalette::Active, QPalette::BrightText, brush7);
        palette27.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette27.setBrush(QPalette::Active, QPalette::Base, brush12);
        palette27.setBrush(QPalette::Active, QPalette::Window, brush12);
        palette27.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette27.setBrush(QPalette::Active, QPalette::AlternateBase, brush8);
        palette27.setBrush(QPalette::Active, QPalette::ToolTipBase, brush9);
        palette27.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
        palette27.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette27.setBrush(QPalette::Inactive, QPalette::Button, brush12);
        palette27.setBrush(QPalette::Inactive, QPalette::Light, brush3);
        palette27.setBrush(QPalette::Inactive, QPalette::Midlight, brush4);
        palette27.setBrush(QPalette::Inactive, QPalette::Dark, brush5);
        palette27.setBrush(QPalette::Inactive, QPalette::Mid, brush6);
        palette27.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette27.setBrush(QPalette::Inactive, QPalette::BrightText, brush7);
        palette27.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette27.setBrush(QPalette::Inactive, QPalette::Base, brush12);
        palette27.setBrush(QPalette::Inactive, QPalette::Window, brush12);
        palette27.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette27.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush8);
        palette27.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush9);
        palette27.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
        palette27.setBrush(QPalette::Disabled, QPalette::WindowText, brush5);
        palette27.setBrush(QPalette::Disabled, QPalette::Button, brush12);
        palette27.setBrush(QPalette::Disabled, QPalette::Light, brush3);
        palette27.setBrush(QPalette::Disabled, QPalette::Midlight, brush4);
        palette27.setBrush(QPalette::Disabled, QPalette::Dark, brush5);
        palette27.setBrush(QPalette::Disabled, QPalette::Mid, brush6);
        palette27.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette27.setBrush(QPalette::Disabled, QPalette::BrightText, brush7);
        palette27.setBrush(QPalette::Disabled, QPalette::ButtonText, brush5);
        palette27.setBrush(QPalette::Disabled, QPalette::Base, brush12);
        palette27.setBrush(QPalette::Disabled, QPalette::Window, brush12);
        palette27.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette27.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush10);
        palette27.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush9);
        palette27.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
        label_36->setPalette(palette27);
        label_36->setStyleSheet(QStringLiteral("background-color : rgb(255, 170, 0);"));
        label_36->setAlignment(Qt::AlignCenter);
        label_34 = new QLabel(frame_info_5);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(130, 40, 16, 71));
        QPalette palette28;
        palette28.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        QBrush brush13(QColor(25, 12, 200, 255));
        brush13.setStyle(Qt::SolidPattern);
        palette28.setBrush(QPalette::Active, QPalette::Button, brush13);
        palette28.setBrush(QPalette::Active, QPalette::Light, brush3);
        palette28.setBrush(QPalette::Active, QPalette::Midlight, brush4);
        palette28.setBrush(QPalette::Active, QPalette::Dark, brush5);
        palette28.setBrush(QPalette::Active, QPalette::Mid, brush6);
        palette28.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette28.setBrush(QPalette::Active, QPalette::BrightText, brush7);
        palette28.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette28.setBrush(QPalette::Active, QPalette::Base, brush13);
        palette28.setBrush(QPalette::Active, QPalette::Window, brush13);
        palette28.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette28.setBrush(QPalette::Active, QPalette::AlternateBase, brush8);
        palette28.setBrush(QPalette::Active, QPalette::ToolTipBase, brush9);
        palette28.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
        palette28.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette28.setBrush(QPalette::Inactive, QPalette::Button, brush13);
        palette28.setBrush(QPalette::Inactive, QPalette::Light, brush3);
        palette28.setBrush(QPalette::Inactive, QPalette::Midlight, brush4);
        palette28.setBrush(QPalette::Inactive, QPalette::Dark, brush5);
        palette28.setBrush(QPalette::Inactive, QPalette::Mid, brush6);
        palette28.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette28.setBrush(QPalette::Inactive, QPalette::BrightText, brush7);
        palette28.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette28.setBrush(QPalette::Inactive, QPalette::Base, brush13);
        palette28.setBrush(QPalette::Inactive, QPalette::Window, brush13);
        palette28.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette28.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush8);
        palette28.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush9);
        palette28.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
        palette28.setBrush(QPalette::Disabled, QPalette::WindowText, brush5);
        palette28.setBrush(QPalette::Disabled, QPalette::Button, brush13);
        palette28.setBrush(QPalette::Disabled, QPalette::Light, brush3);
        palette28.setBrush(QPalette::Disabled, QPalette::Midlight, brush4);
        palette28.setBrush(QPalette::Disabled, QPalette::Dark, brush5);
        palette28.setBrush(QPalette::Disabled, QPalette::Mid, brush6);
        palette28.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette28.setBrush(QPalette::Disabled, QPalette::BrightText, brush7);
        palette28.setBrush(QPalette::Disabled, QPalette::ButtonText, brush5);
        palette28.setBrush(QPalette::Disabled, QPalette::Base, brush13);
        palette28.setBrush(QPalette::Disabled, QPalette::Window, brush13);
        palette28.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette28.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush10);
        palette28.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush9);
        palette28.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
        label_34->setPalette(palette28);
        label_34->setStyleSheet(QStringLiteral("background-color : rgb(25, 12, 200);"));
        label_34->setAlignment(Qt::AlignCenter);
        label_35 = new QLabel(frame_info_5);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(110, 40, 16, 71));
        QPalette palette29;
        palette29.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette29.setBrush(QPalette::Active, QPalette::Button, brush12);
        palette29.setBrush(QPalette::Active, QPalette::Light, brush3);
        palette29.setBrush(QPalette::Active, QPalette::Midlight, brush4);
        palette29.setBrush(QPalette::Active, QPalette::Dark, brush5);
        palette29.setBrush(QPalette::Active, QPalette::Mid, brush6);
        palette29.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette29.setBrush(QPalette::Active, QPalette::BrightText, brush7);
        palette29.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette29.setBrush(QPalette::Active, QPalette::Base, brush12);
        palette29.setBrush(QPalette::Active, QPalette::Window, brush12);
        palette29.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette29.setBrush(QPalette::Active, QPalette::AlternateBase, brush8);
        palette29.setBrush(QPalette::Active, QPalette::ToolTipBase, brush9);
        palette29.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
        palette29.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette29.setBrush(QPalette::Inactive, QPalette::Button, brush12);
        palette29.setBrush(QPalette::Inactive, QPalette::Light, brush3);
        palette29.setBrush(QPalette::Inactive, QPalette::Midlight, brush4);
        palette29.setBrush(QPalette::Inactive, QPalette::Dark, brush5);
        palette29.setBrush(QPalette::Inactive, QPalette::Mid, brush6);
        palette29.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette29.setBrush(QPalette::Inactive, QPalette::BrightText, brush7);
        palette29.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette29.setBrush(QPalette::Inactive, QPalette::Base, brush12);
        palette29.setBrush(QPalette::Inactive, QPalette::Window, brush12);
        palette29.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette29.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush8);
        palette29.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush9);
        palette29.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
        palette29.setBrush(QPalette::Disabled, QPalette::WindowText, brush5);
        palette29.setBrush(QPalette::Disabled, QPalette::Button, brush12);
        palette29.setBrush(QPalette::Disabled, QPalette::Light, brush3);
        palette29.setBrush(QPalette::Disabled, QPalette::Midlight, brush4);
        palette29.setBrush(QPalette::Disabled, QPalette::Dark, brush5);
        palette29.setBrush(QPalette::Disabled, QPalette::Mid, brush6);
        palette29.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette29.setBrush(QPalette::Disabled, QPalette::BrightText, brush7);
        palette29.setBrush(QPalette::Disabled, QPalette::ButtonText, brush5);
        palette29.setBrush(QPalette::Disabled, QPalette::Base, brush12);
        palette29.setBrush(QPalette::Disabled, QPalette::Window, brush12);
        palette29.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette29.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush10);
        palette29.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush9);
        palette29.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
        label_35->setPalette(palette29);
        label_35->setStyleSheet(QStringLiteral("background-color : rgb(255, 170, 0);"));
        label_35->setAlignment(Qt::AlignCenter);
        label_33 = new QLabel(frame_info_5);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(150, 40, 16, 71));
        QPalette palette30;
        palette30.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette30.setBrush(QPalette::Active, QPalette::Button, brush13);
        palette30.setBrush(QPalette::Active, QPalette::Light, brush3);
        palette30.setBrush(QPalette::Active, QPalette::Midlight, brush4);
        palette30.setBrush(QPalette::Active, QPalette::Dark, brush5);
        palette30.setBrush(QPalette::Active, QPalette::Mid, brush6);
        palette30.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette30.setBrush(QPalette::Active, QPalette::BrightText, brush7);
        palette30.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette30.setBrush(QPalette::Active, QPalette::Base, brush13);
        palette30.setBrush(QPalette::Active, QPalette::Window, brush13);
        palette30.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette30.setBrush(QPalette::Active, QPalette::AlternateBase, brush8);
        palette30.setBrush(QPalette::Active, QPalette::ToolTipBase, brush9);
        palette30.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
        palette30.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette30.setBrush(QPalette::Inactive, QPalette::Button, brush13);
        palette30.setBrush(QPalette::Inactive, QPalette::Light, brush3);
        palette30.setBrush(QPalette::Inactive, QPalette::Midlight, brush4);
        palette30.setBrush(QPalette::Inactive, QPalette::Dark, brush5);
        palette30.setBrush(QPalette::Inactive, QPalette::Mid, brush6);
        palette30.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette30.setBrush(QPalette::Inactive, QPalette::BrightText, brush7);
        palette30.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette30.setBrush(QPalette::Inactive, QPalette::Base, brush13);
        palette30.setBrush(QPalette::Inactive, QPalette::Window, brush13);
        palette30.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette30.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush8);
        palette30.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush9);
        palette30.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
        palette30.setBrush(QPalette::Disabled, QPalette::WindowText, brush5);
        palette30.setBrush(QPalette::Disabled, QPalette::Button, brush13);
        palette30.setBrush(QPalette::Disabled, QPalette::Light, brush3);
        palette30.setBrush(QPalette::Disabled, QPalette::Midlight, brush4);
        palette30.setBrush(QPalette::Disabled, QPalette::Dark, brush5);
        palette30.setBrush(QPalette::Disabled, QPalette::Mid, brush6);
        palette30.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette30.setBrush(QPalette::Disabled, QPalette::BrightText, brush7);
        palette30.setBrush(QPalette::Disabled, QPalette::ButtonText, brush5);
        palette30.setBrush(QPalette::Disabled, QPalette::Base, brush13);
        palette30.setBrush(QPalette::Disabled, QPalette::Window, brush13);
        palette30.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette30.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush10);
        palette30.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush9);
        palette30.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
        label_33->setPalette(palette30);
        label_33->setStyleSheet(QStringLiteral("background-color : rgb(25, 12, 200);"));
        label_33->setAlignment(Qt::AlignCenter);
        label_37 = new QLabel(frame_info_5);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(230, 40, 16, 71));
        QPalette palette31;
        palette31.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette31.setBrush(QPalette::Active, QPalette::Button, brush11);
        palette31.setBrush(QPalette::Active, QPalette::Light, brush3);
        palette31.setBrush(QPalette::Active, QPalette::Midlight, brush4);
        palette31.setBrush(QPalette::Active, QPalette::Dark, brush5);
        palette31.setBrush(QPalette::Active, QPalette::Mid, brush6);
        palette31.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette31.setBrush(QPalette::Active, QPalette::BrightText, brush7);
        palette31.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette31.setBrush(QPalette::Active, QPalette::Base, brush11);
        palette31.setBrush(QPalette::Active, QPalette::Window, brush11);
        palette31.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette31.setBrush(QPalette::Active, QPalette::AlternateBase, brush8);
        palette31.setBrush(QPalette::Active, QPalette::ToolTipBase, brush9);
        palette31.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
        palette31.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette31.setBrush(QPalette::Inactive, QPalette::Button, brush11);
        palette31.setBrush(QPalette::Inactive, QPalette::Light, brush3);
        palette31.setBrush(QPalette::Inactive, QPalette::Midlight, brush4);
        palette31.setBrush(QPalette::Inactive, QPalette::Dark, brush5);
        palette31.setBrush(QPalette::Inactive, QPalette::Mid, brush6);
        palette31.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette31.setBrush(QPalette::Inactive, QPalette::BrightText, brush7);
        palette31.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette31.setBrush(QPalette::Inactive, QPalette::Base, brush11);
        palette31.setBrush(QPalette::Inactive, QPalette::Window, brush11);
        palette31.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette31.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush8);
        palette31.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush9);
        palette31.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
        palette31.setBrush(QPalette::Disabled, QPalette::WindowText, brush5);
        palette31.setBrush(QPalette::Disabled, QPalette::Button, brush11);
        palette31.setBrush(QPalette::Disabled, QPalette::Light, brush3);
        palette31.setBrush(QPalette::Disabled, QPalette::Midlight, brush4);
        palette31.setBrush(QPalette::Disabled, QPalette::Dark, brush5);
        palette31.setBrush(QPalette::Disabled, QPalette::Mid, brush6);
        palette31.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette31.setBrush(QPalette::Disabled, QPalette::BrightText, brush7);
        palette31.setBrush(QPalette::Disabled, QPalette::ButtonText, brush5);
        palette31.setBrush(QPalette::Disabled, QPalette::Base, brush11);
        palette31.setBrush(QPalette::Disabled, QPalette::Window, brush11);
        palette31.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette31.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush10);
        palette31.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush9);
        palette31.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
        label_37->setPalette(palette31);
        label_37->setStyleSheet(QStringLiteral("background-color : rgb(0, 85, 127);"));
        label_37->setAlignment(Qt::AlignCenter);
        label_38 = new QLabel(frame_info_5);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(210, 40, 16, 71));
        QPalette palette32;
        palette32.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette32.setBrush(QPalette::Active, QPalette::Button, brush11);
        palette32.setBrush(QPalette::Active, QPalette::Light, brush3);
        palette32.setBrush(QPalette::Active, QPalette::Midlight, brush4);
        palette32.setBrush(QPalette::Active, QPalette::Dark, brush5);
        palette32.setBrush(QPalette::Active, QPalette::Mid, brush6);
        palette32.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette32.setBrush(QPalette::Active, QPalette::BrightText, brush7);
        palette32.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette32.setBrush(QPalette::Active, QPalette::Base, brush11);
        palette32.setBrush(QPalette::Active, QPalette::Window, brush11);
        palette32.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette32.setBrush(QPalette::Active, QPalette::AlternateBase, brush8);
        palette32.setBrush(QPalette::Active, QPalette::ToolTipBase, brush9);
        palette32.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
        palette32.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette32.setBrush(QPalette::Inactive, QPalette::Button, brush11);
        palette32.setBrush(QPalette::Inactive, QPalette::Light, brush3);
        palette32.setBrush(QPalette::Inactive, QPalette::Midlight, brush4);
        palette32.setBrush(QPalette::Inactive, QPalette::Dark, brush5);
        palette32.setBrush(QPalette::Inactive, QPalette::Mid, brush6);
        palette32.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette32.setBrush(QPalette::Inactive, QPalette::BrightText, brush7);
        palette32.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette32.setBrush(QPalette::Inactive, QPalette::Base, brush11);
        palette32.setBrush(QPalette::Inactive, QPalette::Window, brush11);
        palette32.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette32.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush8);
        palette32.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush9);
        palette32.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
        palette32.setBrush(QPalette::Disabled, QPalette::WindowText, brush5);
        palette32.setBrush(QPalette::Disabled, QPalette::Button, brush11);
        palette32.setBrush(QPalette::Disabled, QPalette::Light, brush3);
        palette32.setBrush(QPalette::Disabled, QPalette::Midlight, brush4);
        palette32.setBrush(QPalette::Disabled, QPalette::Dark, brush5);
        palette32.setBrush(QPalette::Disabled, QPalette::Mid, brush6);
        palette32.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette32.setBrush(QPalette::Disabled, QPalette::BrightText, brush7);
        palette32.setBrush(QPalette::Disabled, QPalette::ButtonText, brush5);
        palette32.setBrush(QPalette::Disabled, QPalette::Base, brush11);
        palette32.setBrush(QPalette::Disabled, QPalette::Window, brush11);
        palette32.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette32.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush10);
        palette32.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush9);
        palette32.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
        label_38->setPalette(palette32);
        label_38->setStyleSheet(QStringLiteral("background-color : rgb(0, 85, 127);"));
        label_38->setAlignment(Qt::AlignCenter);
        label_39 = new QLabel(frame_info_5);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(190, 40, 16, 71));
        QPalette palette33;
        palette33.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        QBrush brush14(QColor(170, 85, 255, 255));
        brush14.setStyle(Qt::SolidPattern);
        palette33.setBrush(QPalette::Active, QPalette::Button, brush14);
        palette33.setBrush(QPalette::Active, QPalette::Light, brush3);
        palette33.setBrush(QPalette::Active, QPalette::Midlight, brush4);
        palette33.setBrush(QPalette::Active, QPalette::Dark, brush5);
        palette33.setBrush(QPalette::Active, QPalette::Mid, brush6);
        palette33.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette33.setBrush(QPalette::Active, QPalette::BrightText, brush7);
        palette33.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette33.setBrush(QPalette::Active, QPalette::Base, brush14);
        palette33.setBrush(QPalette::Active, QPalette::Window, brush14);
        palette33.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette33.setBrush(QPalette::Active, QPalette::AlternateBase, brush8);
        palette33.setBrush(QPalette::Active, QPalette::ToolTipBase, brush9);
        palette33.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
        palette33.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette33.setBrush(QPalette::Inactive, QPalette::Button, brush14);
        palette33.setBrush(QPalette::Inactive, QPalette::Light, brush3);
        palette33.setBrush(QPalette::Inactive, QPalette::Midlight, brush4);
        palette33.setBrush(QPalette::Inactive, QPalette::Dark, brush5);
        palette33.setBrush(QPalette::Inactive, QPalette::Mid, brush6);
        palette33.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette33.setBrush(QPalette::Inactive, QPalette::BrightText, brush7);
        palette33.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette33.setBrush(QPalette::Inactive, QPalette::Base, brush14);
        palette33.setBrush(QPalette::Inactive, QPalette::Window, brush14);
        palette33.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette33.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush8);
        palette33.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush9);
        palette33.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
        palette33.setBrush(QPalette::Disabled, QPalette::WindowText, brush5);
        palette33.setBrush(QPalette::Disabled, QPalette::Button, brush14);
        palette33.setBrush(QPalette::Disabled, QPalette::Light, brush3);
        palette33.setBrush(QPalette::Disabled, QPalette::Midlight, brush4);
        palette33.setBrush(QPalette::Disabled, QPalette::Dark, brush5);
        palette33.setBrush(QPalette::Disabled, QPalette::Mid, brush6);
        palette33.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette33.setBrush(QPalette::Disabled, QPalette::BrightText, brush7);
        palette33.setBrush(QPalette::Disabled, QPalette::ButtonText, brush5);
        palette33.setBrush(QPalette::Disabled, QPalette::Base, brush14);
        palette33.setBrush(QPalette::Disabled, QPalette::Window, brush14);
        palette33.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette33.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush10);
        palette33.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush9);
        palette33.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
        label_39->setPalette(palette33);
        label_39->setStyleSheet(QStringLiteral("background-color : rgb(170, 85, 255);"));
        label_39->setAlignment(Qt::AlignCenter);
        label_40 = new QLabel(frame_info_5);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(170, 40, 16, 71));
        QPalette palette34;
        palette34.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette34.setBrush(QPalette::Active, QPalette::Button, brush14);
        palette34.setBrush(QPalette::Active, QPalette::Light, brush3);
        palette34.setBrush(QPalette::Active, QPalette::Midlight, brush4);
        palette34.setBrush(QPalette::Active, QPalette::Dark, brush5);
        palette34.setBrush(QPalette::Active, QPalette::Mid, brush6);
        palette34.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette34.setBrush(QPalette::Active, QPalette::BrightText, brush7);
        palette34.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette34.setBrush(QPalette::Active, QPalette::Base, brush14);
        palette34.setBrush(QPalette::Active, QPalette::Window, brush14);
        palette34.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette34.setBrush(QPalette::Active, QPalette::AlternateBase, brush8);
        palette34.setBrush(QPalette::Active, QPalette::ToolTipBase, brush9);
        palette34.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
        palette34.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette34.setBrush(QPalette::Inactive, QPalette::Button, brush14);
        palette34.setBrush(QPalette::Inactive, QPalette::Light, brush3);
        palette34.setBrush(QPalette::Inactive, QPalette::Midlight, brush4);
        palette34.setBrush(QPalette::Inactive, QPalette::Dark, brush5);
        palette34.setBrush(QPalette::Inactive, QPalette::Mid, brush6);
        palette34.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette34.setBrush(QPalette::Inactive, QPalette::BrightText, brush7);
        palette34.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette34.setBrush(QPalette::Inactive, QPalette::Base, brush14);
        palette34.setBrush(QPalette::Inactive, QPalette::Window, brush14);
        palette34.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette34.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush8);
        palette34.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush9);
        palette34.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
        palette34.setBrush(QPalette::Disabled, QPalette::WindowText, brush5);
        palette34.setBrush(QPalette::Disabled, QPalette::Button, brush14);
        palette34.setBrush(QPalette::Disabled, QPalette::Light, brush3);
        palette34.setBrush(QPalette::Disabled, QPalette::Midlight, brush4);
        palette34.setBrush(QPalette::Disabled, QPalette::Dark, brush5);
        palette34.setBrush(QPalette::Disabled, QPalette::Mid, brush6);
        palette34.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette34.setBrush(QPalette::Disabled, QPalette::BrightText, brush7);
        palette34.setBrush(QPalette::Disabled, QPalette::ButtonText, brush5);
        palette34.setBrush(QPalette::Disabled, QPalette::Base, brush14);
        palette34.setBrush(QPalette::Disabled, QPalette::Window, brush14);
        palette34.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette34.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush10);
        palette34.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush9);
        palette34.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
        label_40->setPalette(palette34);
        label_40->setStyleSheet(QStringLiteral("background-color : rgb(170, 85, 255);"));
        label_40->setAlignment(Qt::AlignCenter);
        label_41 = new QLabel(frame_info_5);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(310, 40, 16, 71));
        QPalette palette35;
        palette35.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette35.setBrush(QPalette::Active, QPalette::Button, brush11);
        palette35.setBrush(QPalette::Active, QPalette::Light, brush3);
        palette35.setBrush(QPalette::Active, QPalette::Midlight, brush4);
        palette35.setBrush(QPalette::Active, QPalette::Dark, brush5);
        palette35.setBrush(QPalette::Active, QPalette::Mid, brush6);
        palette35.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette35.setBrush(QPalette::Active, QPalette::BrightText, brush7);
        palette35.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette35.setBrush(QPalette::Active, QPalette::Base, brush11);
        palette35.setBrush(QPalette::Active, QPalette::Window, brush11);
        palette35.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette35.setBrush(QPalette::Active, QPalette::AlternateBase, brush8);
        palette35.setBrush(QPalette::Active, QPalette::ToolTipBase, brush9);
        palette35.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
        palette35.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette35.setBrush(QPalette::Inactive, QPalette::Button, brush11);
        palette35.setBrush(QPalette::Inactive, QPalette::Light, brush3);
        palette35.setBrush(QPalette::Inactive, QPalette::Midlight, brush4);
        palette35.setBrush(QPalette::Inactive, QPalette::Dark, brush5);
        palette35.setBrush(QPalette::Inactive, QPalette::Mid, brush6);
        palette35.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette35.setBrush(QPalette::Inactive, QPalette::BrightText, brush7);
        palette35.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette35.setBrush(QPalette::Inactive, QPalette::Base, brush11);
        palette35.setBrush(QPalette::Inactive, QPalette::Window, brush11);
        palette35.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette35.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush8);
        palette35.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush9);
        palette35.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
        palette35.setBrush(QPalette::Disabled, QPalette::WindowText, brush5);
        palette35.setBrush(QPalette::Disabled, QPalette::Button, brush11);
        palette35.setBrush(QPalette::Disabled, QPalette::Light, brush3);
        palette35.setBrush(QPalette::Disabled, QPalette::Midlight, brush4);
        palette35.setBrush(QPalette::Disabled, QPalette::Dark, brush5);
        palette35.setBrush(QPalette::Disabled, QPalette::Mid, brush6);
        palette35.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette35.setBrush(QPalette::Disabled, QPalette::BrightText, brush7);
        palette35.setBrush(QPalette::Disabled, QPalette::ButtonText, brush5);
        palette35.setBrush(QPalette::Disabled, QPalette::Base, brush11);
        palette35.setBrush(QPalette::Disabled, QPalette::Window, brush11);
        palette35.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette35.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush10);
        palette35.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush9);
        palette35.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
        label_41->setPalette(palette35);
        label_41->setStyleSheet(QStringLiteral("background-color : rgb(0, 85, 127);"));
        label_41->setAlignment(Qt::AlignCenter);
        label_42 = new QLabel(frame_info_5);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(290, 40, 16, 71));
        QPalette palette36;
        palette36.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette36.setBrush(QPalette::Active, QPalette::Button, brush11);
        palette36.setBrush(QPalette::Active, QPalette::Light, brush3);
        palette36.setBrush(QPalette::Active, QPalette::Midlight, brush4);
        palette36.setBrush(QPalette::Active, QPalette::Dark, brush5);
        palette36.setBrush(QPalette::Active, QPalette::Mid, brush6);
        palette36.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette36.setBrush(QPalette::Active, QPalette::BrightText, brush7);
        palette36.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette36.setBrush(QPalette::Active, QPalette::Base, brush11);
        palette36.setBrush(QPalette::Active, QPalette::Window, brush11);
        palette36.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette36.setBrush(QPalette::Active, QPalette::AlternateBase, brush8);
        palette36.setBrush(QPalette::Active, QPalette::ToolTipBase, brush9);
        palette36.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
        palette36.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette36.setBrush(QPalette::Inactive, QPalette::Button, brush11);
        palette36.setBrush(QPalette::Inactive, QPalette::Light, brush3);
        palette36.setBrush(QPalette::Inactive, QPalette::Midlight, brush4);
        palette36.setBrush(QPalette::Inactive, QPalette::Dark, brush5);
        palette36.setBrush(QPalette::Inactive, QPalette::Mid, brush6);
        palette36.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette36.setBrush(QPalette::Inactive, QPalette::BrightText, brush7);
        palette36.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette36.setBrush(QPalette::Inactive, QPalette::Base, brush11);
        palette36.setBrush(QPalette::Inactive, QPalette::Window, brush11);
        palette36.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette36.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush8);
        palette36.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush9);
        palette36.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
        palette36.setBrush(QPalette::Disabled, QPalette::WindowText, brush5);
        palette36.setBrush(QPalette::Disabled, QPalette::Button, brush11);
        palette36.setBrush(QPalette::Disabled, QPalette::Light, brush3);
        palette36.setBrush(QPalette::Disabled, QPalette::Midlight, brush4);
        palette36.setBrush(QPalette::Disabled, QPalette::Dark, brush5);
        palette36.setBrush(QPalette::Disabled, QPalette::Mid, brush6);
        palette36.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette36.setBrush(QPalette::Disabled, QPalette::BrightText, brush7);
        palette36.setBrush(QPalette::Disabled, QPalette::ButtonText, brush5);
        palette36.setBrush(QPalette::Disabled, QPalette::Base, brush11);
        palette36.setBrush(QPalette::Disabled, QPalette::Window, brush11);
        palette36.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette36.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush10);
        palette36.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush9);
        palette36.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
        label_42->setPalette(palette36);
        label_42->setStyleSheet(QStringLiteral("background-color : rgb(0, 85, 127);"));
        label_42->setAlignment(Qt::AlignCenter);
        label_43 = new QLabel(frame_info_5);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(270, 40, 16, 71));
        QPalette palette37;
        palette37.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette37.setBrush(QPalette::Active, QPalette::Button, brush11);
        palette37.setBrush(QPalette::Active, QPalette::Light, brush3);
        palette37.setBrush(QPalette::Active, QPalette::Midlight, brush4);
        palette37.setBrush(QPalette::Active, QPalette::Dark, brush5);
        palette37.setBrush(QPalette::Active, QPalette::Mid, brush6);
        palette37.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette37.setBrush(QPalette::Active, QPalette::BrightText, brush7);
        palette37.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette37.setBrush(QPalette::Active, QPalette::Base, brush11);
        palette37.setBrush(QPalette::Active, QPalette::Window, brush11);
        palette37.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette37.setBrush(QPalette::Active, QPalette::AlternateBase, brush8);
        palette37.setBrush(QPalette::Active, QPalette::ToolTipBase, brush9);
        palette37.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
        palette37.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette37.setBrush(QPalette::Inactive, QPalette::Button, brush11);
        palette37.setBrush(QPalette::Inactive, QPalette::Light, brush3);
        palette37.setBrush(QPalette::Inactive, QPalette::Midlight, brush4);
        palette37.setBrush(QPalette::Inactive, QPalette::Dark, brush5);
        palette37.setBrush(QPalette::Inactive, QPalette::Mid, brush6);
        palette37.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette37.setBrush(QPalette::Inactive, QPalette::BrightText, brush7);
        palette37.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette37.setBrush(QPalette::Inactive, QPalette::Base, brush11);
        palette37.setBrush(QPalette::Inactive, QPalette::Window, brush11);
        palette37.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette37.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush8);
        palette37.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush9);
        palette37.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
        palette37.setBrush(QPalette::Disabled, QPalette::WindowText, brush5);
        palette37.setBrush(QPalette::Disabled, QPalette::Button, brush11);
        palette37.setBrush(QPalette::Disabled, QPalette::Light, brush3);
        palette37.setBrush(QPalette::Disabled, QPalette::Midlight, brush4);
        palette37.setBrush(QPalette::Disabled, QPalette::Dark, brush5);
        palette37.setBrush(QPalette::Disabled, QPalette::Mid, brush6);
        palette37.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette37.setBrush(QPalette::Disabled, QPalette::BrightText, brush7);
        palette37.setBrush(QPalette::Disabled, QPalette::ButtonText, brush5);
        palette37.setBrush(QPalette::Disabled, QPalette::Base, brush11);
        palette37.setBrush(QPalette::Disabled, QPalette::Window, brush11);
        palette37.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette37.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush10);
        palette37.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush9);
        palette37.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
        label_43->setPalette(palette37);
        label_43->setStyleSheet(QStringLiteral("background-color : rgb(0, 85, 127);"));
        label_43->setAlignment(Qt::AlignCenter);
        label_44 = new QLabel(frame_info_5);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(250, 40, 16, 71));
        QPalette palette38;
        palette38.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette38.setBrush(QPalette::Active, QPalette::Button, brush11);
        palette38.setBrush(QPalette::Active, QPalette::Light, brush3);
        palette38.setBrush(QPalette::Active, QPalette::Midlight, brush4);
        palette38.setBrush(QPalette::Active, QPalette::Dark, brush5);
        palette38.setBrush(QPalette::Active, QPalette::Mid, brush6);
        palette38.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette38.setBrush(QPalette::Active, QPalette::BrightText, brush7);
        palette38.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette38.setBrush(QPalette::Active, QPalette::Base, brush11);
        palette38.setBrush(QPalette::Active, QPalette::Window, brush11);
        palette38.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette38.setBrush(QPalette::Active, QPalette::AlternateBase, brush8);
        palette38.setBrush(QPalette::Active, QPalette::ToolTipBase, brush9);
        palette38.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
        palette38.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette38.setBrush(QPalette::Inactive, QPalette::Button, brush11);
        palette38.setBrush(QPalette::Inactive, QPalette::Light, brush3);
        palette38.setBrush(QPalette::Inactive, QPalette::Midlight, brush4);
        palette38.setBrush(QPalette::Inactive, QPalette::Dark, brush5);
        palette38.setBrush(QPalette::Inactive, QPalette::Mid, brush6);
        palette38.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette38.setBrush(QPalette::Inactive, QPalette::BrightText, brush7);
        palette38.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette38.setBrush(QPalette::Inactive, QPalette::Base, brush11);
        palette38.setBrush(QPalette::Inactive, QPalette::Window, brush11);
        palette38.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette38.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush8);
        palette38.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush9);
        palette38.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
        palette38.setBrush(QPalette::Disabled, QPalette::WindowText, brush5);
        palette38.setBrush(QPalette::Disabled, QPalette::Button, brush11);
        palette38.setBrush(QPalette::Disabled, QPalette::Light, brush3);
        palette38.setBrush(QPalette::Disabled, QPalette::Midlight, brush4);
        palette38.setBrush(QPalette::Disabled, QPalette::Dark, brush5);
        palette38.setBrush(QPalette::Disabled, QPalette::Mid, brush6);
        palette38.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette38.setBrush(QPalette::Disabled, QPalette::BrightText, brush7);
        palette38.setBrush(QPalette::Disabled, QPalette::ButtonText, brush5);
        palette38.setBrush(QPalette::Disabled, QPalette::Base, brush11);
        palette38.setBrush(QPalette::Disabled, QPalette::Window, brush11);
        palette38.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette38.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush10);
        palette38.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush9);
        palette38.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
        label_44->setPalette(palette38);
        label_44->setStyleSheet(QStringLiteral("background-color : rgb(0, 85, 127);"));
        label_44->setAlignment(Qt::AlignCenter);
        MainWindow->setCentralWidget(centralWidget);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 994, 19));
        menuPlanificador_de_Procesos_CSUNSA = new QMenu(menuBar);
        menuPlanificador_de_Procesos_CSUNSA->setObjectName(QStringLiteral("menuPlanificador_de_Procesos_CSUNSA"));
        menuAyuda = new QMenu(menuBar);
        menuAyuda->setObjectName(QStringLiteral("menuAyuda"));
        MainWindow->setMenuBar(menuBar);

        menuBar->addAction(menuPlanificador_de_Procesos_CSUNSA->menuAction());
        menuBar->addAction(menuAyuda->menuAction());

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "CPU Scheduler", 0));
        actionFile->setText(QApplication::translate("MainWindow", "File", 0));
        label->setText(QApplication::translate("MainWindow", "Informacion", 0));
        label_7->setText(QApplication::translate("MainWindow", "# de Tareas", 0));
        label_8->setText(QApplication::translate("MainWindow", "Algoritmo", 0));
        label_9->setText(QApplication::translate("MainWindow", "Velocidad de sim", 0));
        label_10->setText(QApplication::translate("MainWindow", "Quantum", 0));
        pushButton->setText(QApplication::translate("MainWindow", "Simular", 0));
        pushButton_2->setText(QApplication::translate("MainWindow", "Detener", 0));
        pushButton_3->setText(QApplication::translate("MainWindow", "Siguiente Paso", 0));
        pushButton_4->setText(QApplication::translate("MainWindow", "Reiniciar", 0));
        pushButton_5->setText(QApplication::translate("MainWindow", "Comenzar otra simulacion", 0));
        pushButton_6->setText(QApplication::translate("MainWindow", "Terminar", 0));
        label_2->setText(QApplication::translate("MainWindow", "Tareas", 0));
        QTableWidgetItem *___qtablewidgetitem = tabla_tareas->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QApplication::translate("MainWindow", "#", 0));
        QTableWidgetItem *___qtablewidgetitem1 = tabla_tareas->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QApplication::translate("MainWindow", "Llegada", 0));
        QTableWidgetItem *___qtablewidgetitem2 = tabla_tareas->horizontalHeaderItem(2);
        ___qtablewidgetitem2->setText(QApplication::translate("MainWindow", "Burst", 0));
        QTableWidgetItem *___qtablewidgetitem3 = tabla_tareas->horizontalHeaderItem(3);
        ___qtablewidgetitem3->setText(QApplication::translate("MainWindow", "Prioridad", 0));
        QTableWidgetItem *___qtablewidgetitem4 = tabla_tareas->horizontalHeaderItem(4);
        ___qtablewidgetitem4->setText(QApplication::translate("MainWindow", "Comienzo", 0));
        QTableWidgetItem *___qtablewidgetitem5 = tabla_tareas->horizontalHeaderItem(5);
        ___qtablewidgetitem5->setText(QApplication::translate("MainWindow", "Espera", 0));
        QTableWidgetItem *___qtablewidgetitem6 = tabla_tareas->horizontalHeaderItem(6);
        ___qtablewidgetitem6->setText(QApplication::translate("MainWindow", "Restante", 0));
        QTableWidgetItem *___qtablewidgetitem7 = tabla_tareas->horizontalHeaderItem(7);
        ___qtablewidgetitem7->setText(QApplication::translate("MainWindow", "Termina", 0));
        QTableWidgetItem *___qtablewidgetitem8 = tabla_tareas->horizontalHeaderItem(8);
        ___qtablewidgetitem8->setText(QApplication::translate("MainWindow", "Cambio", 0));
        QTableWidgetItem *___qtablewidgetitem9 = tabla_tareas->horizontalHeaderItem(9);
        ___qtablewidgetitem9->setText(QApplication::translate("MainWindow", "%", 0));

        const bool __sortingEnabled = tabla_tareas->isSortingEnabled();
        tabla_tareas->setSortingEnabled(false);
        tabla_tareas->setSortingEnabled(__sortingEnabled);

        label_3->setText(QApplication::translate("MainWindow", "CPU", 0));
        label_11->setText(QApplication::translate("MainWindow", "Tarea Actual", 0));
        label_12->setText(QApplication::translate("MainWindow", "Tiempo Actual", 0));
        label_13->setText(QApplication::translate("MainWindow", "Utilizacion", 0));
        label_19->setText(QApplication::translate("MainWindow", "JOB 0", 0));
        label_20->setText(QApplication::translate("MainWindow", "0", 0));
        label_21->setText(QApplication::translate("MainWindow", "0 %", 0));
        label_4->setText(QApplication::translate("MainWindow", "En cola", 0));
        label_24->setText(QApplication::translate("MainWindow", "<--", 0));
        label_16->setText(QApplication::translate("MainWindow", "5", 0));
        label_17->setText(QApplication::translate("MainWindow", "3", 0));
        label_5->setText(QApplication::translate("MainWindow", "Promedio", 0));
        label_14->setText(QApplication::translate("MainWindow", "Esperando", 0));
        label_15->setText(QApplication::translate("MainWindow", "Retorno", 0));
        label_22->setText(QApplication::translate("MainWindow", "0.00", 0));
        label_23->setText(QApplication::translate("MainWindow", "0.00", 0));
        label_6->setText(QApplication::translate("MainWindow", "Grafica Gantt", 0));
        label_18->setText(QApplication::translate("MainWindow", "1", 0));
        label_25->setText(QApplication::translate("MainWindow", "1", 0));
        label_26->setText(QApplication::translate("MainWindow", "1", 0));
        label_27->setText(QApplication::translate("MainWindow", "1", 0));
        label_36->setText(QApplication::translate("MainWindow", "2", 0));
        label_34->setText(QApplication::translate("MainWindow", "3", 0));
        label_35->setText(QApplication::translate("MainWindow", "2", 0));
        label_33->setText(QApplication::translate("MainWindow", "3", 0));
        label_37->setText(QApplication::translate("MainWindow", "5", 0));
        label_38->setText(QApplication::translate("MainWindow", "5", 0));
        label_39->setText(QApplication::translate("MainWindow", "4", 0));
        label_40->setText(QApplication::translate("MainWindow", "4", 0));
        label_41->setText(QApplication::translate("MainWindow", "5", 0));
        label_42->setText(QApplication::translate("MainWindow", "5", 0));
        label_43->setText(QApplication::translate("MainWindow", "5", 0));
        label_44->setText(QApplication::translate("MainWindow", "5", 0));
        menuPlanificador_de_Procesos_CSUNSA->setTitle(QApplication::translate("MainWindow", "Archivo", 0));
        menuAyuda->setTitle(QApplication::translate("MainWindow", "Ayuda", 0));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
